### PR TITLE
Sprint 1 Team 8 301

### PR DESCRIPTION
**Pull request by Kapperchino**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please undo changes to runServer.sh. This is not related to your changes.

**Comment by Kapperchino** [comment]
We needed to change it so it works with linux

**Comment by Bhargavicm** [comment]
Since all the teams have the same change in that file. We will do a generic check-in so please undo it from your end.

**Comment by Kapperchino** [comment]
Its removal of a semi colon, which should be changed on every branch in the first place. It was broken, we needed it to make the project work on linux.

**Comment by Kapperchino** [comment]
I changed the sh file back, it should be fine now

**Comment by gildir** [comment]
Please resolve conflicts for this pull request.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on this pull request.

**Pull request closed without merging**
