### PR TITLE
111 and 116

### PR DESCRIPTION
**Pull request by rpowell99**
Combined Main Story, add rooms to default map, and item dropping error fix. Combined because the Main Story relies on the addition of more rooms

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by rpowell99** [comment]
Conflicts resolved as of 9:00 11/19/18

**Comment by Bhargavicm** [comment]
Reverting, below error on server build.

GameObjectInterface.java:510: error: illegal start of type
     * Returns a Shop's "In Demand" inventory as a formatted string
     ^
GameObjectInterface.java:510: error: = expected
     * Returns a Shop's "In Demand" inventory as a formatted string
       ^
GameObjectInterface.java:510: error: ';' expected
     * Returns a Shop's "In Demand" inventory as a formatted string
              ^
GameObjectInterface.java:510: error: unclosed character literal
     * Returns a Shop's "In Demand" inventory as a formatted string
                     ^
GameObjectInterface.java:510: error: ';' expected
     * Returns a Shop's "In Demand" inventory as a formatted string
                       ^
GameObjectInterface.java:510: error: = expected
     * Returns a Shop's "In Demand" inventory as a formatted string
                                                 ^
GameObjectInterface.java:511: error: = expected
     * @param id The shop ID
     ^
GameObjectInterface.java:511: error: = expected
     * @param id The shop ID
                     ^
GameObjectInterface.java:511: error: <identifier> expected
     * @param id The shop ID
                            ^
GameObjectInterface.java:512: error: = expected
     * @return A formatted string representing the Shop's "In Deman" inventory
     ^
GameObjectInterface.java:512: error: ';' expected
     * @return A formatted string representing the Shop's "In Deman" inventory
      ^
GameObjectInterface.java:512: error: illegal start of type
     * @return A formatted string representing the Shop's "In Deman" inventory
        ^
GameObjectInterface.java:512: error: = expected
     * @return A formatted string representing the Shop's "In Deman" inventory
                 ^
GameObjectInterface.java:512: error: = expected
     * @return A formatted string representing the Shop's "In Deman" inventory
                                               ^
GameObjectInterface.java:512: error: unclosed character literal
     * @return A formatted string representing the Shop's "In Deman" inventory
                                                       ^
GameObjectInterface.java:512: error: ';' expected
     * @return A formatted string representing the Shop's "In Deman" inventory
                                                         ^
GameObjectInterface.java:512: error: <identifier> expected
     * @return A formatted string representing the Shop's "In Deman" inventory
                                                                              ^
GameObjectInterface.java:513: error: = expected
     */
     ^
GameObjectInterface.java:513: error: ';' expected
     */

**Comment by rpowell99** [comment]
That's a missing comment block /*. Probably would've been easier for both of us if to just fix it instead of reverting the whole thing. Could you give me advice on how to get git to allow me to merge back in my changes, because this revert is part of the history now and it wants to revert all my changes whenever I try to merge

**Pull request merged**
