### PR TITLE
Team-3 Section-004 Sprint-2 | 211 heartbeat

### PR DESCRIPTION
**Pull request by whMason**

### CODE REVIEW

**Comment by gildir** [comment]
Please resolve conflicts for this pull request.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on this pull request.

**Comment by whMason** [comment]
Waiting for our sprint one to me merged before resolving, no need to resolve formatting changes twice.

**Comment by Bhargavicm** [comment]
I would suggest you, do not resolve conflicts as of now and wait until your Sprint 1 items go in first. For now, work on sprint 1 resolution, if you think you need to wait until other teams put their sprint 1 first then please coordinate with teams to know your wait time.

**Comment by whMason** [comment]
If you believe dev is good, aka not going to revert it, let me know and I'll start work on these, thanks.

**Comment by Bhargavicm** [comment]
Dev is all good. Your sprint 1 changes and the other item to ignore player has been merged successfully.

**Comment by Bhargavicm** [comment]
Shall I go ahead and merge this item?

**Comment by whMason** [comment]
One minute fixing a little format

**Comment by whMason** [comment]
Should be good to merge.

**Pull request merged**
