### PR TITLE
Team 3 Sprint 1 Post-Revert

### PR DESCRIPTION
**Pull request by whMason**

### CODE REVIEW

**Comment by whMason** [comment]
Theres nothing I can seem to do to get this to work. If I create a new branch with the resolved code it tries to replace every file. If I try to just fix the small thing needed to get this to work it conflicts, which means I have to pull dev which reverts my change so then the resolved version removes all of my changes.

**Comment by Bhargavicm** [comment]
I don't see any conflicts now. Are you still working/testing or is this ready to merge?

**Comment by whMason** [comment]
I believe this is ready.

**Comment by Bhargavicm** [comment]
Merged successfully. Let's do sprint 2 now. Notify in your comments to each pull request which item needs to fo first from your sprint 2 and I will merge accordingly.

**Pull request merged**
