### PR TITLE
605c generate cshops

### PR DESCRIPTION
**Pull request by Repker**

### CODE REVIEW

**Comment by gildir** [comment]
Please resolve conflicts for this pull request.

**Comment by zazyzaya** [comment]
Fixed merge conflicts

**Comment by zazyzaya** [comment]
Fixed merge conflicts

**Comment by Bhargavicm** [comment]
I find merge conflicts on all your submissions. Please fix the conflicts with the latest Dev code. I had to consider Team 1 as a priority due to their dependency as per discussion with Professor. Please resolve all your conflicts.

**Pull request closed without merging**
