### PR TITLE
Completed Pull Request for 103

### PR DESCRIPTION
**Pull request by cwells21**
These additions complete 103

### CODE REVIEW

**Comment by gildir** [comment]
Please resolve conflicts for this pull request.

**Comment by cwells21** [comment]
Resolved the conflicts and I am submiting a pull request from dev.

**Comment by cwells21** [comment]
Looks like a case of an old version with changes merging with a new version.  I made the necessary changes.

**Comment by Bhargavicm** [comment]
I find merge conflicts your submissions. Please fix the conflicts with the latest Dev code. I had to consider Team 1 as a priority due to their dependency as per discussion with Professor. Please resolve all your conflicts.

**Pull request closed without merging**
