### PR TITLE
This will work, Team 1 all features

### PR DESCRIPTION
**Pull request by malikbrown78**

### CODE REVIEW

**Comment by malikbrown78** [comment]
This merge retains the Ghoul and ghost functions as well as adds features
502-C
F-03
501
509-A
506
502
502-A
505
503
502
504

**Comment by Bhargavicm** [comment]
I see a lot of commented code on GameCore.java. Could you please revert and update as required. I see no difference from commented code to what you have added in some of the lines.

**Comment by malikbrown78** [comment]
The commented code belongs to other teams and I didn’t want to delete their stuff but I had to edit it out to get the code to work with the Item object versus the string object.

For some of the other method calls, I simply changed String to Item so there wasn’t much difference.

**Comment by malikbrown78** [comment]
A good example is the bribeGhoul method. It used a String from the inventory to determine its Boolean status “giveAble”, I had to change a few lines to make it work with the Item Object now. I didn’t delete their code, just commented it out because while I had to edit it to make it work, I didn’t want the group to lose their work.

Second is the givetoGhoul method. The team who created it even admitted it was redundant and didn’t have a function yet, so instead of changing it, I just commented it out so they can use it in later features down the road

**Comment by Bhargavicm** [comment]
Ok, sounds good.

**Pull request merged**
