### PR TITLE
313 player custom command

### PR DESCRIPTION
**Pull request by Kapperchino**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by Bhargavicm** [comment]
Please resolve merge conflicts on this one.

**Comment by Bhargavicm** [comment]
Merge conflicts on this file src/GameClient.java

**Comment by Kapperchino** [comment]
Done

**Comment by Bhargavicm** [comment]
I don't think this file log 10-31-2018.txt should be a part of this pull request. This is a log file to be created irrespective of this.

**Comment by Kapperchino** [comment]
got rid of it

**Pull request merged**
