### PR TITLE
Team-3 Section-004 Sprint-1

### PR DESCRIPTION
**Pull request by whMason**
Had to remake previous attempt

Contains 201, 202, 203, 204, 205, and 206; We received permission to have all features in the same pull from professor Russell.
We expect there will be conflicts with saving our player class. We request our branch is merged last, so that we may resolve any conflicts while maintaining the save function.

### CODE REVIEW

**Comment by gildir** [comment]
Please resolve conflicts for this pull request.

**Comment by whMason** [comment]
I did my best to resolve these conflicts. The previous team was allowed to commit many formatting changes which made it difficult to see what the differences really were.

**Comment by whMason** [comment]
Strong feeling if this is merged the sprint 2 pulls will have different conflicts. Unless told otherwise will wait for this merge before resolving sprint 2 pulls.

**Comment by Bhargavicm** [comment]
Since you have requested to merge your changes at the end of everyone's sprint one, I will still wait until others resolve their conflicts to merge yours. You might have to wait to resolve conflicts until others do. But if you think its okay to merge before other teams do then please let me know and I will go ahead and merge.

**Comment by whMason** [comment]
Originally I would have liked to have merged last to ensure the json marshalling would work correctly after everyone made their changes to the player class, but at this point with this chaos I'm starting to care less. Might as well just make a bug fix for anything broken in sprint 4.

**Comment by Bhargavicm** [comment]
But if your changes would break the application then I would not recommend doing it at this point. Wait for merges until my first cycle tomorrow and then resolve conflicts. I will merge your changes accordingly.

**Comment by Bhargavicm** [comment]
Looks like yours is the only team without sprint 1 merged. Is it safe to merge now? If so please resolve your conflicts and I will do a merge. If not I would wait until Saturday morning and have your teams merge of both sprint 1 and 2. Let me know what you think.

**Comment by whMason** [comment]
Having issues getting a proper merge done tonight, will revisit tomorrow.

**Comment by Bhargavicm** [comment]
Is this pull request ready to merge? Let me know if you are still working on it.

**Comment by Bhargavicm** [comment]
Some observations:
1) You have a Readme file attached, not required for this feature.
2) I see jar files in there, are these necessary for your changes?
3) Most of the files have the spacing conflicts. If you could resolve them to avoid conflicts with other teams, that would be great.

**Comment by whMason** [comment]
1. Removed README
2. Yes, they are libraries we use for marshalling, have instructors approval for those
3. To which spacing conflicts are you referring to? I only really see code changes in my diff

**Comment by whMason** [comment]
Nevermind, I see the formatting. I must have had ignore space changes on in egit, will fix.

**Comment by Bhargavicm** [comment]
I merged one of the other teams waiting. Please resolve the conflicts and remove the unwanted files for these features in this pull request. Also, please update in your comments if it is ready for review and merge.

**Comment by whMason** [comment]
Merged, ready for review.

**Comment by whMason** [comment]
NOTE
Ignored players should really be an arraylist of strings. These won't be saved for future logins until this is changed.

**Comment by whMason** [comment]
So on my branch it builds and the server runs. If you are talking about an error message like this
```java -cp ".;../lib/*" -Djava.security.policy=game.policy GameServer localhost
Error: Could not find or load main class GameServer```
Then the build script failed. Since my build script works, I cant know what the issue is. Could you please comment the output of your build script?

**Comment by Bhargavicm** [comment]
Below is the error message:
Error: Could not find or load main class GameServer

**Comment by whMason** [comment]
Is there an error with the build script?

**Comment by Bhargavicm** [comment]
No error when I build. When I run the server it shows the error mentioned above.

**Comment by whMason** [comment]
Alright, I see this doesn't happen on windows but on linux. Not quite sure, looking into it.

**Comment by Bhargavicm** [comment]
Sure. Make a new pull request once this is fixed, I will no longer be getting notifications for the closed requests.

**Pull request merged**
