### PR TITLE
Team-3 Section-004 Sprint-2 | 20[7-9] friend system

### PR DESCRIPTION
**Pull request by whMason**

### CODE REVIEW

**Comment by gildir** [comment]
Please resolve conflicts for this pull request.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on this pull request.

**Comment by whMason** [comment]
Waiting for our sprint one to me merged before resolving, no need to resolve formatting changes twice.

**Comment by whMason** [comment]
Resolved but testing definitely needed. _Interesting_ merge

**Comment by Bhargavicm** [comment]
Shall I wait for you to finish testing or go ahead and merge?

**Comment by whMason** [comment]
Sorry, did some very quick tests. I'd say go ahead and merge.

**Pull request merged**
