### PR TITLE
601a shop at clocktower

### PR DESCRIPTION
**Pull request by Repker**
hopefully the .sh files and the .gitignore work

### CODE REVIEW

**Comment by Bhargavicm** [comment]
I would suggest removing the commented code from Shop.java. If you are not using that code, it doesn't have to stay there.

**Comment by Repker** [comment]
the commented code in Shop.java has been removed

**Comment by zazyzaya** [comment]
Fixed merge conflicts

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by zazyzaya** [comment]
Fixed conflicts. Note this branch is mostly depreciated by now. Merge this before 605c and let the 605 branch overwrite whatever it needs to

**Comment by Bhargavicm** [comment]
I find merge conflicts on all your submissions. Please fix the conflicts with the latest Dev code. I had to consider Team 1 as a priority due to their dependency as per discussion with Professor. Please resolve all your conflicts.

**Pull request closed without merging**
