### PR TITLE
Team-3 Section-004 Sprint-2 | 212 ignore players folder

### PR DESCRIPTION
**Pull request by whMason**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts on this pull request.

**Comment by whMason** [comment]
Waiting for our sprint one to me merged before resolving, no need to resolve formatting changes twice.

**Comment by whMason** [comment]
Ready for merge. (btw I'm at work but Im doing my best to get these done)

**Comment by Bhargavicm** [comment]
Merged.

**Pull request merged**
