### PR TITLE
Peer review

### PR DESCRIPTION
**Pull request by cwells21**
Submitting pull request for the changes requested in the peer review.
1. Changed the name of addRoom to Map Generator
2. Added commenting.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve merge conflicts for this pull request.

**Comment by gildir** [comment]
This pull request appears to be deleting large amounts of code (for the bank, etc.). Can you please verify why:
    Changed the name of addRoom to Map Generator
    Added commenting.
Are doing this?

**Comment by cwells21** [comment]
Removed instances where my file did not agree (Removed my changes and retained gildir/dev).  It looks like there was a merge after I commented the code.

**Comment by cwells21** [comment]
I have cloned dev, and then copied the comments into this clone.  Then I have added the name change to the map generator.  I have submitted a new pull request.

________________________________

**Pull request closed without merging**
