### PR TITLE
Team2 - Sprint 1 & 2 **Please consider merging asap!

### PR DESCRIPTION
**Pull request by pschemer**
Due to the nature of our features, each one depends on another. Therefore, our PR branches are getting extremely large!

Please consider pulling in these changes as a priority as the work is just too much.

**Sprint 2:
Feature # - Title - Primary Author - Note**
Feature 403 - Chat Log - Brandon/Patrick - All chat features from #37 and here required for functionality.
Feature 409 - Word Filter - Reed - All chat features from #37 and here required for functionality.
Feature 410 - Joke - Schuyler
Feature 411 - Shout - Carl

**Sprint 1:
Feature -- Author -- Previous PR# -- Blocker/Explanation**
401_Whisper -- Patrick -- 18 -- "root" branch, no blocker
404_QuickReply -- Brandon -- 20 -- Requires 401_Whisper to function
405_Ignore -- Reed -- 21 -- Requires 401_Whisper to confirm functionality
406_IgnoredMe -- Patrick -- 22 -- Requires 401_Whisper and 405_Ignore to function
407_IgnoreList -- Carl -- 23 -- Requires 405_Ignore to function
408_Unignore -- Carl -- 24 -- Requires 405_Ignore to function and 407_IgnoreList to confirm functionality

### CODE REVIEW

**Comment by Bhargavicm** [comment]
I had to consider Team 1's pull request as the priority due to their code-breaking by many teams in discussion with Professor. 

In this pull request, I see that you have merged sprint 1 and 2 together. I would not recommend doing that unless no feature of yours can be independent. If you still think it cant be separate then please resolve the conflicts on this one and revert. I will merge them as soon as I get your next request during my merging window.

**Comment by pschemer** [comment]
This can once again merge without conflict:
! **** NOTE: There is an error that may cause /dev/ to not compile or function correctly.

GameCoreInterface.java
(dev) L. 117
--- or now (sprint2) --- L. 168
 * @throws RemoteException.

Suggestion: Delete this line since offer(String, String, String) does not throw any exception.

**Comment by Bhargavicm** [comment]
I see conflicts on two files src/GameClient.java
src/GameObjectInterface.java. Please resolve.

**Comment by pschemer** [comment]
Conflicts resolved as of merge of PR #82 .
Moved instruction commands to help.xml to reflect new feature.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on below files:
src/GameClient.java
src/GameCore.java
src/GameCoreInterface.java
src/GameObject.java
src/GameObjectInterface.java
src/help.xml

**Comment by Bhargavicm** [comment]
Merge conflicts exist.

**Comment by Bhargavicm** [comment]
Give me a heads up when you finish resolving conflicts by commenting "Ready to merge" or "Conflicts resolved".

**Comment by pschemer** [comment]
I kept this current going three weeks but that last PR merged in just killed it.  I've merged in your /dev/ four times since then and git still claims conflicts.  Using "git diff", the only changes are either white-space out of my control or necessary changes. Any advice is appreciated but I must step away from this as its severely affecting my other classes.

**Comment by pschemer** [comment]
This can merge again - the issue was a file permissions change.

**Comment by pschemer** [comment]
Ready to merge + fixed the problem with a previous PR change to GameServer.java that prevented the project from compiling.

**Comment by Bhargavicm** [comment]
You may want to remove the runServer.sh file from this as it does not fall under your feature.

**Comment by pschemer** [comment]
Was runServer.sh removed in a prior PR? I did not create nor have made changes to this file.

**Comment by Bhargavicm** [comment]
But was this a feature request? I remember one of the teams had this as a bug fix. Not sure if that was your team. Looks like you have made changes in your local and file is carried away in your pull request. Please delete that file from this pull request.

**Comment by pschemer** [comment]
Checked out your version of runServer.sh. Should be an exact match.

**Comment by pschemer** [comment]
<3

**Comment by Bhargavicm** [comment]
Huge merge!!! - Successful

**Pull request merged**
