### PR TITLE
Team2 Sprint2

### PR DESCRIPTION
**Pull request by pschemer**
Note: If [PR #37](https://github.com/gildir/CS321-2018F-004/pull/37)  hasn't been merged yet, this PR contains the previous as a base since all previous changes were required for these features as well.

Unique from PR#37, this request includes:
**- Feature # - Title - Primary Author - Note**
- Feature 403 - Chat Log - Brandon/Patrick - All chat features from #37 and here required for functionality.
- Feature 409 - Word Filter - Reed - All chat features from #37 and here required for functionality.
- Feature 410 - Joke - Schuyler
- Feature 411 - Shout - Carl

### CODE REVIEW

**Comment by gildir** [comment]
Please resolve conflicts for this pull request.

**Comment by pschemer** [comment]
I'm confused regarding our PR's #37 #38 #63 
As of last night, these PR's could be merged automatically. #37 and #38 were previously deemed 'OK' and just waiting on other teams. 

- It looks like some changes were pulled into /dev/ that added some trivial whitespace for whatever reason, causing conflicts to our PR's. Would "git merge -Xignore-space-change " not suffice?

- Github claims there are conflicts with src/rooms.xml yet none of our PR's have modified this file.

Do you want me to move forward by pulling in the whitespace changes to our branch(es), merge all your changes with our repo, and then push back up?

Do you & Professor Russell want us to resolve both #37 #63 separately still? Recall, #63 (Sprint 2) contains all of the code in #37 (Sprint 1) due to dependencies.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on previous dependencies before you fix this pull request.

**Comment by pschemer** [comment]
I've made another round of merges to my branch but I'm very hesitant to push them to our repo. Can we at least ensure feature branches compile before merging them? The current iteration of upstream/dev/ doesn't compile, here is a list of 'first glance' issues regarding the most recent change to /dev/:

‘First glance’ issues:
General:
- [as always] numerous, trivial whitespace changes
- duplicate library imports, not updating javadoc parameters when making a change, removing functions when unnecessary. 
- Sidenote: Why was it necessary to remove references to direction rather than just not use it in [___] feature?

Specific:
GameClient:
- Missing '}' to close out else{ in "case: "ACCEPT":"
- Weirdly decide to move the POKE/BRIBE GHOUL commands before the instruction set despite ‘Ghouls & Ghosts’ team’s original placement.

GameCore & ...Interface:
- leave(String) defined twice
- move(..) javadoc not updated to reflect new parameter
- challenge(..) and accept(..) document a "challenge" parameter rather than "challengee"
- @override right(String) no longer overrides from superclass [b/c it was arbitrarily removed].
- @override left(String) no longer overrides from superclass [b/c it was arbitrarily removed].

GameObject & ...Interface:
- move(..) same issue as GameCore
- doesn’t declare or abstract method “left (String)” & likely others dealing with Direction.

Fixing these changes will cause conflicts to our PR's. Do we accept these changes?

**Pull request closed without merging**
