### PR TITLE
102 world files

### PR DESCRIPTION
**Pull request by rpowell99**
Team 6 Sprint 2: 102 World Files
Adds a command line argument to specify which file to load the world from

### CODE REVIEW

**Comment by gildir** [comment]
Please resolve conflicts for this pull request.

**Comment by rpowell99** [comment]
Resolved merge conflicts in GameCore.java

**Comment by Bhargavicm** [comment]
Please resolve conflicts on this pull request.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on this pull request.

**Comment by rpowell99** [comment]
Resolved conflicts again, I don't know when these happened but could you comment me next time so I can get them resolved? I had already fixed the one's from 4 days ago, I guess I should've commented that also

**Comment by Bhargavicm** [comment]
Conflicts again. These conflicts will keep coming if I merge any requests before yours. Please have them resolved.

**Pull request merged**
