### PR TITLE
Team 2 402_PlayerList

### PR DESCRIPTION
**Pull request by pschemer**
Per your request, I'm resubmitting PR's in the desired format. 
This particular PR only includes feature 402_PlayerList
402_PlayerList does not have any blockers/dependencies.

Team 2 Sprint 1 approved features pre-merged for convenience. This branch includes previous PR's for the following work:

Feature -- Author -- PR#
402 -- Schuyler -- 19

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Looks good. Waiting for other teams to resolve conflicts and then we would merge.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on this pull request.

**Comment by pschemer** [comment]
Conflicts resolved as of PR #82 merge.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on below files
src/GameClient.java
src/GameCore.java
src/help.xml

**Comment by pschemer** [comment]
Hopefully this is good to go as well.

**Comment by Bhargavicm** [comment]
I see GameClient.java  file just has the spacing conflicts. Please remove it from your pull request if their are no code changes.

**Comment by Bhargavicm** [comment]
Please pull the latest as per dev and check if your code is working as required and then I would do a merge when you are all done. Just give me a thumbs up when done.

**Comment by pschemer** [comment]
Rebuilt and merged. Should be OK now.

**Comment by pschemer** [comment]
Thank you!

**Comment by Bhargavicm** [comment]
All set - No errors.

**Pull request merged**
