### PR TITLE
Shop readme

### PR DESCRIPTION
**Pull request by Repker**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
You need to remove changes for files build.bat and build.sh as they are not part of your sprint 3.

**Comment by gildir** [comment]
Reminder: You need to remove changes for files build.bat and build.sh as they are not part of your sprint 3.

**Comment by gildir** [comment]
Reminder: You need to remove changes for files build.bat and build.sh as they are not part of your sprint 3.

**Comment by Bhargavicm** [comment]
Reminder: You need to remove changes for files build.bat and build.sh as they are not part of your sprint 3.

**Comment by Bhargavicm** [comment]
Please exclude src/clean.bat and src/build.bat from your pull request.

**Pull request closed without merging**
