### PR TITLE
New peer

### PR DESCRIPTION
**Pull request by cwells21**
Tested the files before the merge.  Sorry for the delay.  For some reason it will not let me correct merge issues.  Which is just commenting.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
This pull request has conflicts. You will need to fix the conflicts for me to merge.

**Comment by cwells21** [comment]
I can not resolve.  the system is locked and giving me:

Only those with write access to this repository can merge pull requests.

**Comment by cwells21** [comment]
That should fix it.

**Comment by Bhargavicm** [comment]
I think you used the auto merge from Git. You can see the //<<<<<<< HEAD inserted in your files. I suggest you to use the following link to see on resolving the same. You will need to manually edit those files. 

https://stackoverflow.com/questions/10657315/git-merge-left-head-marks-in-my-files

**Comment by cwells21** [comment]
I commented those out in vim. I left as a reference.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Bhargavicm** [comment]
Please consider removing them manually.

**Comment by cwells21** [comment]
I just uploaded a new version without the headers.


________________________________

**Pull request closed without merging**
