### PR TITLE
102 world files

### PR DESCRIPTION
**Pull request by rpowell99**
New pull request for 102 world files, I removed the semicolon in runServer.sh as you requested.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Is this part of your feature? There is a team that has this as a bug fix. Please close this pull request if this is not your feature.

**Comment by rpowell99** [comment]
The semicolon fix is not part of my feature, but on my last pull request you said to take it out and you would merge it. I'm adding it back now.

**Comment by Bhargavicm** [comment]
I am closing this pull request as it has changes only to runServer.sh file and not required at the moment.

**Comment by rpowell99** [comment]
It only shows changes to runServer because the other changes were merge in and reverted.

**Pull request closed without merging**
