### PR TITLE
307 logfile and 311a whiteboard

### PR DESCRIPTION
**Pull request by Kapperchino**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by Kapperchino** [comment]
I'll wait on this one because it requires every other branch

**Comment by Kapperchino** [comment]
I got it to work with every command now I think

**Comment by Bhargavicm** [comment]
Please undo your changes to runServer.sh as this is not related to any of your features. Also, your hrlp.xml files comment out the initial game description. Was that change requested?

**Comment by Kapperchino** [comment]
I got rid of the comment because the other xml files didn't have them, I'll revert the runserver.sh

**Comment by Kapperchino** [comment]
Its done

**Pull request merged**
